=== kristovatlas/threat-model-scoring-system/threat model schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://openbitcoinprivacyproject.org/threatmodel_v3#",
    "title": "OBPP Threat Model V3",
    "description": "A threat model specification",
    "type": "object",
    "required": [ "name", "description", "attackers", "countermeasures", "criteria" ],
    "properties": {
        "name": {
            "description": "The name of the threat model",
            "type": "string",
            "minLength": 1
        },
        "description": {
            "description": "A description of the threat model.",
            "type": "string",
            "minLength": 1
        },
        "attackers": {
            "description": "A list of attackers in the threat model",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "object",
                "required": [ "numeral", "name", "weight" ],
                "properties": {
                    "numeral": {
                        "description": "A unique uppercase Roman numeral that identifies this attacker, such as 'I'",
                        "type": "string",
                        "minLength": 1,
                        "pattern": "^M{0,4}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$"
                    },
                    "name": {
                        "description": "Unique name for this attacker",
                        "type": "string"
                    },
                    "weight": {
                        "description": "Weight assigned to attacker compared to other attackers.",
                        "type": "integer",
                        "minimum": 0
                    },
                    "nonce-id": {
                        "description": "An optional field that uniquely identifies an attacker between different versions of a threat model in order to facilitate threat model development",
                        "type": "string"
                    },
                    "tags": {
                        "description": "An optional list of tags for this attacker",
                        "type": "array",
                        "uniqueItems": true,
                        "items": {
                            "type": "string",
                            "minLength": 1
                        }
                    },
                    "attacks": {
                        "description": "Attacks performed by attackers",
                        "type": "array",
                        "minItems": 1,
                        "uniqueItems": true,
                        "items": {
                            "type": "object",
                            "required": [ "numeral", "name", "weight" ],
                            "properties": {
                                "numeral": {
                                    "description": "Unique uppercase letter or letters that identifies this attack, such as 'A'",
                                    "type": "string",
                                    "minLength": 1,
                                    "pattern": "^[A-Z]+$"
                                },
                                "name": {
                                    "description": "Unique name for this attack",
                                    "type": "string"
                                },
                                "weight": {
                                    "description": "Weight assigned to this attack compared to other attacks under this particular attacker.",
                                    "type": "integer",
                                    "minimum": 0
                                },
                                "nonce-id": {
                                    "description": "An optional field that uniquely identifies an attack between different versions of a threat model in order to facilitate threat model development",
                                    "type": "string"
                                },
                                "tags": {
                                    "description": "An optional list of tags for this attack",
                                    "type": "array",
                                    "uniqueItems": true,
                                    "items": {
                                        "type": "string",
                                        "minLength": 1
                                    }
                                },
                                "countermeasures": {
                                    "description": "A countermeasure that partially or wholly mitigates an attack",
                                    "type": "array",
                                    "uniqueItems": true,
                                    "required": ["criteria-groups", "criteria"],
                                    "items": {
                                        "type": "object",
                                        "required": [ "numeral", "id", "effectiveness" ],
                                        "oneOf": [
                                            { "required": [ "criteria-groups" ] },
                                            { "required": [ "criteria" ]}
                                        ],
                                        "properties": {
                                            "numeral": {
                                                "description": "Unique number that identifies this countermeasure, such as '1'",
                                                "type": "string",
                                                "pattern": "^[1-9][0-9]*$"
                                            },
                                            "effectiveness": {
                                                "description": "A decimal expressing the percentage which the countermeasure defends against an attack if successfully implemented.",
                                                "type": "number",
                                                "minimum": 0,
                                                "maximum": 1
                                            },
                                            "identifier": {
                                                "description": "A unique string that identifies a single countermeasure that may be common to multiple attacks in one or more attack categories",
                                                "type": "string",
                                                "pattern": "^[a-zA-Z0-9_\\-]+$"
                                            },
                                            "tags": {
                                                "description": "An optional list of tags for this countermeasure as it applies to the parent attack specifically",
                                                "type": "array",
                                                "uniqueItems": true,
                                                "items": {
                                                    "type": "string",
                                                    "minLength": 1
                                                }
                                            },
                                            "criteria-groups": {
                                                "type": "array",
                                                "uniqueItems": true,
                                                "items": {
                                                    "$ref": "#/definitions/criteria-group"
                                                }
                                            },
                                            "criteria": {
                                                "type": "array",
                                                "uniqueItems": true,
                                                "items": {
                                                    "$ref": "#/definitions/criterion-ref"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "countermeasures": {
            "description": "A complete list of countermeasures against attacks in the threat model",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "object",
                "required": [ "id", "description" ],
                "properties": {
                    "id": {
                        "description": "A unique string identifying this countermeasure.",
                        "type": "string",
                        "minLength": 1
                    },
                    "description": {
                        "description": "A human-readable description of this countermeasure.",
                        "type": "string",
                        "minLength": 1
                    },
                    "comment": {
                        "description": "An optional, human-readable string explaining more about this countermeasure.",
                        "type": "string",
                        "minLength": 1
                    },
                    "tags": {
                        "description": "An optional list of tags for this countermeasure",
                        "type": "array",
                        "uniqueItems": true,
                        "items": {
                            "type": "string",
                            "minLength": 1
                        }
                    },
                    "nonce-id": {
                        "description": "An optional field that uniquely identifies a countermeasure between different versions of a threat model in order to facilitate threat model development",
                        "type": "string"
                    }
                }
            }
        },
        "criteria": {
            "description": "A complete list of criteria for satisfying countermeasures",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "object",
                "required": [ "id", "description" ],
                "properties": {
                    "id": {
                        "description": "A unique string identifying this criterion.",
                        "type": "string",
                        "minLength": 1
                    },
                    "description": {
                        "description": "A human-readable description of this criterion.",
                        "type": "string",
                        "minLength": 1
                    },
                    "comment": {
                        "description": "An optional, human-readable string explaining more about this criterion.",
                        "type": "string",
                        "minLength": 1
                    },
                    "tags": {
                        "description": "An optional list of tags for this criterion",
                        "type": "array",
                        "uniqueItems": true,
                        "items": {
                            "type": "string",
                            "minLength": 1
                        }
                    },
                    "nonce-id": {
                        "description": "An optional field that uniquely identifies a criterion between different versions of a threat model in order to facilitate threat model development",
                        "type": "string"
                    }
                }
            }
        },
        "tags": {
            "description": "An optional list of tags that can be applied to attackers, attacks, countermeasures, or criteria and which may be optionally displayed in generated documentation",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "object",
                "required": [ "name" ],
                "properties": {
                    "id": {
                        "description": "A unique string identifying this tag",
                        "type": "string",
                        "minLength": 1
                    },
                    "name": {
                        "description": "The actual tag",
                        "type": "string",
                        "minLength": 1
                    },
                    "comment": {
                        "description": "An optional, human-readable string explaining more about this tag",
                        "type": "string",
                        "minLength": 1
                    },
                    "nonce-id": {
                        "description": "An optional field that uniquely identifies a tag between different versions of a threat model in order to facilitate threat model development",
                        "type": "string"
                    },
                    "print-in-docs": {
                        "description": "This specifies whether tags should be displayed along side the threat model elements they've tagged in documentation. If not specified, the default value is `true`",
                        "type": "boolean"
                    }
                }
            }
        }
    },
    "definitions": {
        "criteria-group": {
            "description": "A group containing criteria and/or child criteria-groups",
            "properties": {
                "criteria": {
                    "description": "A list of criteria that satisfy this criteria-group. The effectiveness of each applicable criterion is summed to a maximum of 100% for this criteria-group.",
                    "type": "array",
                    "uniqueItems": true,
                    "items": {
                        "$ref": "#/definitions/criterion-ref"
                    }
                }
            }
        },
        "criterion-ref": {
            "description": "A criterion listed under a parent countermeasure, referring to an object in the document's `criteria` array",
            "required": [ "id", "description" ],
            "properties": {
                "numeral": {
                    "description": "Unique lowercase letter or letters that identifies this category, such as 'a'",
                    "type": "string",
                    "minLength": 1,
                    "pattern": "^[a-z]+$"
                },
                "id": {
                    "description": "A unique string identifying this countermeasure that MUST match an id of a criterion object listed in the document's 'criteria' array.",
                    "type": "string",
                    "minLength": 1
                },
                "description": {
                    "description": "Summary of the criterion",
                    "type": "string"
                },
                "tags": {
                    "description": "An optional list of tags for this criterion as it applies to the parent countermeasure",
                    "type": "array",
                    "uniqueItems": true,
                    "items": {
                        "type": "string",
                        "minLength": 1
                    }
                },
                "effectiveness": {
                    "description": "A decimal expressing the percentage which the criterion satisfies a countermeasure if successfully implemented.",
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                }
            }
        },
        "criteria-groups": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/criteria-group"
            }
        }
    }
}

=== kristovatlas/threat-model-scoring-system/test/unlisted_countermeasure.json
{
    "name": "Ninja-Ghost V1 Threat Model with unlisted countermeasure",
    "description": "Ninja-Ghost V1 Threat Model: A silly example of a threat model for enemy attacks on a game character.",
    "attackers": [
        {
            "numeral": "I",
            "name": "Ninja",
            "weight": 2,
            "comment": "A Ninja is twice as dangerous as a ghost.",
            "attacks": [
                {
                    "numeral": "A",
                    "name": "Punch",
                    "weight": 1,
                    "countermeasures": [
                        {
                            "numeral": "1",
                            "id": "NINJAGHOSTV1-CM1",
                            "description": "Block attacks",
                            "effectiveness": 1.0,
                            "criteria-groups": [
                                {
                                    "criteria": [
                                        {
                                            "numeral": "a",
                                            "id": "NINJAGHOSTV1-CR1",
                                            "description": "Evades attacks completely",
                                            "effectiveness": 1.0
                                        }
                                    ]
                                },
                                {
                                    "criteria": [
                                        {
                                            "numeral": "b",
                                            "id": "NINJAGHOSTV1-CR2",
                                            "description": "Crosses arms in front of body when attacked",
                                            "effectiveness": 0.5
                                        },
                                        {
                                            "numeral": "c",
                                            "id": "NINJAGHOSTV1-CR3",
                                            "description": "Assumes fetal position when attacked",
                                            "effectiveness": 0.1
                                        }
                                    ],
                                    "comment": "You can cross your arms and assume the fetal position at the same time."
                                }
                            ],
                            "comment": "You cannot assume the fetal position or block with your arms and evade attacks completely simultaneously."
                        },
                        {
                            "numeral": "2",
                            "id": "NINJAGHOSTV1-CM2",
                            "description": "Counter-punch",
                            "effectiveness": 0.5,
                            "criteria-groups": [
                                {
                                    "criteria": [
                                        {
                                            "numeral": "a",
                                            "id": "NINJAGHOSTV1-CR4",
                                            "description": "Throws uppercut when punched at",
                                            "effectiveness": 1.0
                                        }
                                    ]
                                },
                                {
                                    "criteria": [
                                        {
                                            "numeral": "b",
                                            "id": "NINJAGHOSTV1-CR5",
                                            "description": "Throws right hook when punched at",
                                            "effectiveness": 0.7
                                        }
                                    ]
                                }
                            ],
                            "comment": "You cannot throw an uppercut and a right hook at the same time. Also, uppercuts are more effective against ninjas than right hooks."
                        },
                        {
                            "numeral": "3",
                            "id": "NINJAGHOSTV1-CM3",
                            "description": "Teleport",
                            "effectiveness": 1.0,
                            "criteria-groups": [
                                {
                                    "criteria": [
                                        {
                                            "numeral": "a",
                                            "id": "NINJAGHOSTV1-CR6",
                                            "description": "Magically relocates five feet when attacked",
                                            "effectiveness": 0.5
                                        },
                                        {
                                            "numeral": "b",
                                            "id": "NINJAGHOSTV1-CR1",
                                            "description": "Evades attacks completely",
                                            "effectiveness": 1.0
                                        }
                                    ],
                                    "comment": "You can both relocate and evade completely, but teleporting only five feet away is less effective by itself."
                                }
                            ]
                        }
                    ]
                },
                {
                    "numeral": "B",
                    "name": "Criticize",
                    "weight": 0,
                    "comment": "Criticism is not dangerous at all (weight = 0)."
                }
            ]
        },
        {
            "numeral": "II",
            "name": "Ghost",
            "weight": 1,
            "comment": "A ghost is half as dangerous as a ninja.",
            "attacks": [
                {
                    "numeral": "A",
                    "name": "Make scary noises",
                    "weight": 1,
                    "countermeasures": [
                        {
                            "numeral": "1",
                            "id": "NINJAGHOSTV1-CM4",
                            "description": "Assume defensive posture",
                            "effectiveness": 1.0,
                            "criteria-groups": [
                                {
                                    "criteria": [
                                        {
                                            "numeral": "a",
                                            "id": "NINJAGHOSTV1-CR7",
                                            "description": "Wears earplugs",
                                            "effectiveness": 1.0
                                        },
                                        {
                                            "numeral": "b",
                                            "id": "NINJAGHOSTV1-CR3",
                                            "description": "Assumes fetal position when attacked",
                                            "effectiveness": 0.1
                                        }
                                    ]
                                }
                            ],
                            "comment": "You can simultaneously assume the fetal position and wear earplugs, but the former alone is not effective."
                        }
                    ]
                },
                {
                    "numeral": "B",
                    "name": "Drop an anvil",
                    "weight": 10,
                    "countermeasures": [
                        {
                            "numeral": "1",
                            "id": "NINJAGHOSTV1-CM4",
                            "description": "Assume defensive posture",
                            "effectiveness": 0.5,
                            "criteria-groups": [
                                {
                                    "numeral": "a",
                                    "id": "NINJAGHOSTV1-CR2",
                                    "description": "Crosses arms in front of body when attacked",
                                    "effectiveness": 1.0
                                }
                            ]
                        }
                    ],
                    "comment": "Assuming a defensive posture when getting hit by an anvil has limited effectiveness."
                }
            ],
            "comment": "Falling anvils are 10x more dangerous than scary noises."
        }
    ],
    "countermeasures": [
        {
            "id": "NINJAGHOSTV1-CM1",
            "description": "Block attacks"
        },
        {
            "id": "NINJAGHOSTV1-CM2",
            "description": "Counter-punch"
        },
        {
            "id": "NINJAGHOSTV1-CM3",
            "description": "Teleport"
        },
        {
            "id": "NINJAGHOSTV1-CM4",
            "description": "Assume defensive posture"
        },
        {
            "id": "NINJAGHOSTV1-CM5",
            "description": "Unlisted countermeasure"
        }
    ],
    "criteria": [
        {
            "id": "NINJAGHOSTV1-CR1",
            "description": "Evades attacks completely"
        },
        {
            "id": "NINJAGHOSTV1-CR2",
            "description": "Crosses arms in front of body when attacked"
        },
        {
            "id": "NINJAGHOSTV1-CR3",
            "description": "Assumes fetal position when attacked"
        },
        {
            "id": "NINJAGHOSTV1-CR4",
            "description": "Throws uppercut when punched at"
        },
        {
            "id": "NINJAGHOSTV1-CR5",
            "description": "Throws right hook when punched at"
